server:
  port: 8082
management:
  server:
    port: 9003
    address: 127.0.0.1
spring:
  application:
    name: product-active-ms
  data:
    mongodb:
      url: mongodb://localhost:27017
      database: product_active_bd
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 30
    leaseExpirationDurationInSeconds: 90