server:
  port: 8081
management:
  server:
    port: 9002
    address: 127.0.0.1
spring:
  application:
    name: product-pasive-ms
  data:
    mongodb:
      url: mongodb://localhost:27017
      database: product_pasive_bd
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 30
    leaseExpirationDurationInSeconds: 90
